### PR TITLE
Add Altcha support

### PR DESCRIPTION
**Pull request by grantholle**
This PR integrates [Altcha](https://altcha.org/) into the package.

### CODE REVIEW

**Comment by aryehraber** [comment]
Nice one, @grantholle! I hadn't heard of Altcha before, looks cool 👌 

Happy to review this PR once you're ready, will leave it for now since it's a "Draft".

**Comment by grantholle** [comment]
Yeah, I've had to do something a little hacky to get it to work with Vue and my site. It seems to work, but I don't _love_ it. If you look at `resources/views/altcha/head.blade.php`, I'm basically waiting until the DOM is loaded then injecting it manually.

It's working on the site I'm testing with, but feels a little wrong to do it that way. However, when I do it the right way, Vue renderers it twice. I think to fix it, I'm going to have to refactor my frontend and how I'm using Vue. You can see [the issue](https://github.com/altcha-org/altcha/issues/7) I made for it, but I discovered it's Vue's fault.

**Comment by aryehraber** [comment]
Yeah, using Statamic Captcha in an SPA/Ajax setup hasn't been a great experience tbh. 

I've had issues in the past having Vue & Alpine.js play nice with reCaptcha & hCaptcha due to similar reasons. It's been a little while now, but I think I had the opposite problem, where NO captcha would load due to Vue/Alpine.js not being ready at the "right" time.

I ended up taking manual control from within my JS code in those cases. For example, I would exclude Captcha's tags and run the necessary captcha init & execution code myself from inside the Vue component. I kind of explained it in an issue a while ago, but probably could use a full explanation in Captcha's docs... https://github.com/aryehraber/statamic-captcha/issues/14#issuecomment-1025766126 -- what you end up with is just using this addon as a backend, and handling the frontend yourself.

Hope that makes sense/helps!

**Comment by aryehraber** [comment]
Hey @grantholle, hope you're well! Saw some activity here recently, is there still interest in getting this merged? Or are you simply using your forked version and want to close this PR?

**Comment by grantholle** [comment]
Yeah I think it's ready for review. We've been using in production since I created the PR and it seems to be working fine. I recently updated to Statamic 5 so I updated this PR. You can see it in action [here](https://yhischina.com/contact).

**Comment by aryehraber** [comment]
Awesome, thanks! I'll try and find some time in the next week or 2 to merge and create a new release, since I'll also have to update the docs with relevant links etc. Appreciate it!

**Comment by aryehraber** [comment]
Thanks again @grantholle! 

Took me a few moments to understand how Altcha worked to verify your implementation, was a little different than the other captcha services. Ended up refactoring a couple of small bits but all-in-all this was great 👌 

I've just released Captcha v1.13.0 with these changes 🚀

**Comment by grantholle** [comment]
@aryehraber Thanks so much! Glad it made it in

**Pull request merged**
